### ISSUE TITLE
Migrate margin modules to OCA?

### ISSUE THREAD

**Issue by rafaelbn** [akretion/odoo-usability#31]
Hi @alexis-via ,

I would like to know what do you think about migrating this modules to OCA:

- https://github.com/akretion/odoo-usability/tree/10.0/sale_margin_report
- https://github.com/akretion/odoo-usability/tree/10.0/sale_margin_no_onchange
- https://github.com/akretion/odoo-usability/tree/10.0/account_invoice_margin
- https://github.com/akretion/odoo-usability/tree/10.0/account_invoice_margin_report

We haven't analyzed yet, but the could be of general interest. Don't you think so?

Let me know please
Thanks

cc @sergio-teruel @pedrobaeza @carlosdaduden @Tecnativa

**Comment by alexis-via** [comment]
In fact, the modules sale_margin_no_onchange and account_invoice_margin are not in the OCA because there are already some modules that are supposed to do that in the OCA, cf https://github.com/OCA/margin-analysis and https://github.com/OCA/sale-financial

I have some experience with the OCA modules of the project "sale-financial" and I will never use those modules again ! They are too big, too complex, difficult to understand. It probably explains why nobody bothered to port them to v8, v9 nor v10. And the modules of the "margin-analysis" project are also a bit complex. That's why I decided to develop those small/simple modules that are suitable for my customer's need.

But, in the OCA, we don't want to have several modules for the same feature (and that's an important rule). So, if we introduce those modules in the OCA, that would mean removing those old "dinosaure" modules... which is not an easy decision.

In the meantime, I'll continue to maintain them in my usability branch (and I will certainly port them to v10)... But don't get me wrong, I would be very happy to move these modules in the OCA, I'm just not willing to start a big debate about the removal of the "dinosaure" modules of sale-financial and margin-analysis.

**Comment by pedrobaeza** [comment]
@rafaelbn as this hasn't been done finally, please close it.
