### ISSUE TITLE
would you consider contributing product_variant_csv_import to OCA/product-attribute?

### ISSUE THREAD

**Issue by lepistone** [akretion/odoo-usability#6]
Title says it all. Thanks for the great work!

**Comment by alexis-via** [comment]
Sorry, I read this ticket only now... I missed it during my August holidays.

Of course, you can move any module of odoo-usability to OCA. Once you succeed in moving them to OCA, I'll remove them from here, to avoid confusion.

My branch odoo-usability contains modules that I don't propose to OCA because:
- module is too small
- may not gather a large agreement of reviewers on a technical or functional point of view
- because I'm too lazy to propose them and fight during several months to get a review and a merge in OCA (some modules may not be "worth" it).

**Comment by alexis-via** [comment]
It may also contain module that I plan to propose to OCA once they are mature.

For this module product_variant_csv_import, I didn't propose it to OCA because it's too small and I thought it wasn't worth the effort.

**Comment by eLBati** [comment]
@lepistone I'm working on https://github.com/OCA/product-variant/pull/15

**Comment by sebastienbeau** [comment]
This have been merged
